
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.Table table2;

	private global::Gtk.Button add;

	private global::Gtk.Button divide;

	private global::Gtk.Button multi;

	private global::Gtk.Button rand;

	private global::Gtk.Button sub;

	private global::Gtk.Entry textbox1;

	private global::Gtk.Entry textbox2;

	private global::Gtk.Entry textbox3;

	private global::Gtk.Label GtkLabel4;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame2 = new global::Gtk.Frame();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.table2 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.add = new global::Gtk.Button();
		this.add.CanFocus = true;
		this.add.Name = "add";
		this.add.UseUnderline = true;
		this.add.Label = global::Mono.Unix.Catalog.GetString("ADD");
		this.table2.Add(this.add);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2[this.add]));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.divide = new global::Gtk.Button();
		this.divide.CanFocus = true;
		this.divide.Name = "divide";
		this.divide.UseUnderline = true;
		this.divide.Label = global::Mono.Unix.Catalog.GetString("DIVIDE");
		this.table2.Add(this.divide);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2[this.divide]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(2));
		w2.RightAttach = ((uint)(3));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.multi = new global::Gtk.Button();
		this.multi.CanFocus = true;
		this.multi.Name = "multi";
		this.multi.UseUnderline = true;
		this.multi.Label = global::Mono.Unix.Catalog.GetString("MULTIPLY");
		this.table2.Add(this.multi);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2[this.multi]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.rand = new global::Gtk.Button();
		this.rand.CanFocus = true;
		this.rand.Name = "rand";
		this.rand.UseUnderline = true;
		this.rand.Label = global::Mono.Unix.Catalog.GetString("RANDOM");
		this.table2.Add(this.rand);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2[this.rand]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		w4.LeftAttach = ((uint)(2));
		w4.RightAttach = ((uint)(3));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.sub = new global::Gtk.Button();
		this.sub.CanFocus = true;
		this.sub.Name = "sub";
		this.sub.UseUnderline = true;
		this.sub.Label = global::Mono.Unix.Catalog.GetString("SUBTRACT");
		this.table2.Add(this.sub);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2[this.sub]));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.textbox1 = new global::Gtk.Entry();
		this.textbox1.CanFocus = true;
		this.textbox1.Name = "textbox1";
		this.textbox1.IsEditable = true;
		this.textbox1.InvisibleChar = '•';
		this.table2.Add(this.textbox1);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2[this.textbox1]));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.textbox2 = new global::Gtk.Entry();
		this.textbox2.CanFocus = true;
		this.textbox2.Name = "textbox2";
		this.textbox2.IsEditable = true;
		this.textbox2.InvisibleChar = '•';
		this.table2.Add(this.textbox2);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2[this.textbox2]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.textbox3 = new global::Gtk.Entry();
		this.textbox3.CanFocus = true;
		this.textbox3.Events = ((global::Gdk.EventMask)(256));
		this.textbox3.Name = "textbox3";
		this.textbox3.IsEditable = true;
		this.textbox3.InvisibleChar = '•';
		this.table2.Add(this.textbox3);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2[this.textbox3]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(3));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment.Add(this.table2);
		this.frame2.Add(this.GtkAlignment);
		this.GtkLabel4 = new global::Gtk.Label();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.Xalign = 0F;
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Calc</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel4;
		this.Add(this.frame2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 128;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.sub.Clicked += new global::System.EventHandler(this.subBtn);
		this.rand.Clicked += new global::System.EventHandler(this.ranBtn);
		this.multi.Clicked += new global::System.EventHandler(this.mtpBtn);
		this.divide.Clicked += new global::System.EventHandler(this.divBtn);
		this.add.Clicked += new global::System.EventHandler(this.addBtn);
	}
}
