# Generated by Django 2.2.4 on 2019-10-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='members',
            field=models.ManyToManyField(to='members.Member'),
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(to='members.Member'),
        ),
        migrations.AddField(
            model_name='event',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
