# Generated by Django 2.2.6 on 2019-10-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=200)),
                ('pet_type', models.CharField(max_length=200)),
                ('pets_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Owner')),
            ],
        ),
    ]
